module.exports.NAVIGATE_TO_PAGE = 'QT-NAVIGATE';
module.exports.BREAKING_NEWS_UPDATED = 'QT-BREAKING_NEWS_UPDATED';
module.exports.CLIENT_SIDE_RENDERED = 'QT-CLIENT_SIDE_RENDERED';
module.exports.PAGE_LOADING = 'QT-PAGE_LOADING';
module.exports.PAGE_FINISHED_LOADING = 'QT-PAGE_FINISHED_LOADING';

module.exports.HAMBURGER_CLICKED = 'QT-HAMBURGER_CLICKED';
module.exports.HAMBURGER_CLOSED = 'QT-HAMBURGER_CLOSED';
